export const TAST_ADDED = 'taskAdded'
export const TASK_DELETED = 'taskDeleted'
export const TASK_MODIFIED = 'taskModified'
export const TASK_FINISHED = 'taskFinished'
export const TASK_LOADED = 'taskLoaded'